<?php

namespace DoctrineProxies\__CG__\Siacme\Dominio\Consultas;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CobroConsulta extends \Siacme\Dominio\Consultas\CobroConsulta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Siacme\\Dominio\\Consultas\\CobroConsulta' . "\0" . 'id', '' . "\0" . 'Siacme\\Dominio\\Consultas\\CobroConsulta' . "\0" . 'consulta', 'costo', 'pago', 'cambio', 'formaPago', 'fechaPago', 'abono'];
        }

        return ['__isInitialized__', '' . "\0" . 'Siacme\\Dominio\\Consultas\\CobroConsulta' . "\0" . 'id', '' . "\0" . 'Siacme\\Dominio\\Consultas\\CobroConsulta' . "\0" . 'consulta', 'costo', 'pago', 'cambio', 'formaPago', 'fechaPago', 'abono'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CobroConsulta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsulta', []);

        return parent::getConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function registrarPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registrarPago', []);

        return parent::registrarPago();
    }

    /**
     * {@inheritDoc}
     */
    public function getCosto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosto', []);

        return parent::getCosto();
    }

    /**
     * {@inheritDoc}
     */
    public function getPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPago', []);

        return parent::getPago();
    }

    /**
     * {@inheritDoc}
     */
    public function getCambio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCambio', []);

        return parent::getCambio();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormaPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormaPago', []);

        return parent::getFormaPago();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPago', []);

        return parent::getFechaPago();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbono', []);

        return parent::getAbono();
    }

    /**
     * {@inheritDoc}
     */
    public function enEfectivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'enEfectivo', []);

        return parent::enEfectivo();
    }

    /**
     * {@inheritDoc}
     */
    public function montoPago($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'montoPago', [$monto]);

        return parent::montoPago($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function formaPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'formaPago', []);

        return parent::formaPago();
    }

}
