<?php

namespace DoctrineProxies\__CG__\Siacme\Dominio\Expedientes;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Odontograma extends \Siacme\Dominio\Expedientes\Odontograma implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'dientes', 'revisado', 'expedienteEspecialidad'];
        }

        return ['__isInitialized__', 'id', 'dientes', 'revisado', 'expedienteEspecialidad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Odontograma $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarDiente(\Siacme\Dominio\Expedientes\Diente $diente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarDiente', [$diente]);

        return parent::agregarDiente($diente);
    }

    /**
     * {@inheritDoc}
     */
    public function removerPadecimientosADiente($numeroDiente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removerPadecimientosADiente', [$numeroDiente]);

        return parent::removerPadecimientosADiente($numeroDiente);
    }

    /**
     * {@inheritDoc}
     */
    public function agregarPadecimientoADiente($numeroDiente, \Siacme\Dominio\Expedientes\DientePadecimiento $dientePadecimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarPadecimientoADiente', [$numeroDiente, $dientePadecimiento]);

        return parent::agregarPadecimientoADiente($numeroDiente, $dientePadecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function diente($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'diente', [$numero]);

        return parent::diente($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function revisado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'revisado', []);

        return parent::revisado();
    }

    /**
     * {@inheritDoc}
     */
    public function getDientes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDientes', []);

        return parent::getDientes();
    }

    /**
     * {@inheritDoc}
     */
    public function borrarDientesTratamientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'borrarDientesTratamientos', []);

        return parent::borrarDientesTratamientos();
    }

    /**
     * {@inheritDoc}
     */
    public function generarPara(\Siacme\Dominio\Expedientes\ExpedienteJohanna $expedienteJohanna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generarPara', [$expedienteJohanna]);

        return parent::generarPara($expedienteJohanna);
    }

}
