<?php

namespace DoctrineProxies\__CG__\Siacme\Dominio\Consultas;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Consulta extends \Siacme\Dominio\Consultas\Consulta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'id', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'padecimientoActual', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'interrogatorioAparatosSistemas', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'exploracionFisica', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'notaMedica', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'comportamientoFrankl', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'costo', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'pagada', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'comentario', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'costos', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'receta', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'expediente', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'consultaCosto', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'fecha', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'medico', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'cobrosConsulta', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'otrosCostos', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'aRealizarEnProximaCita', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'higieneDentalConsulta', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'indicacionConsulta'];
        }

        return ['__isInitialized__', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'id', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'padecimientoActual', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'interrogatorioAparatosSistemas', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'exploracionFisica', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'notaMedica', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'comportamientoFrankl', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'costo', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'pagada', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'comentario', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'costos', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'receta', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'expediente', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'consultaCosto', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'fecha', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'medico', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'cobrosConsulta', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'otrosCostos', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'aRealizarEnProximaCita', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'higieneDentalConsulta', '' . "\0" . 'Siacme\\Dominio\\Consultas\\Consulta' . "\0" . 'indicacionConsulta'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Consulta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPadecimientoActual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadecimientoActual', []);

        return parent::getPadecimientoActual();
    }

    /**
     * {@inheritDoc}
     */
    public function getInterrogatorioAparatosSistemas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterrogatorioAparatosSistemas', []);

        return parent::getInterrogatorioAparatosSistemas();
    }

    /**
     * {@inheritDoc}
     */
    public function getExploracionFisica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExploracionFisica', []);

        return parent::getExploracionFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotaMedica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotaMedica', []);

        return parent::getNotaMedica();
    }

    /**
     * {@inheritDoc}
     */
    public function getComportamientoFrankl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComportamientoFrankl', []);

        return parent::getComportamientoFrankl();
    }

    /**
     * {@inheritDoc}
     */
    public function pagada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pagada', []);

        return parent::pagada();
    }

    /**
     * {@inheritDoc}
     */
    public function getComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentario', []);

        return parent::getComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function getCosto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosto', []);

        return parent::getCosto();
    }

    /**
     * {@inheritDoc}
     */
    public function cortesia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cortesia', []);

        return parent::cortesia();
    }

    /**
     * {@inheritDoc}
     */
    public function getReceta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceta', []);

        return parent::getReceta();
    }

    /**
     * {@inheritDoc}
     */
    public function tieneReceta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneReceta', []);

        return parent::tieneReceta();
    }

    /**
     * {@inheritDoc}
     */
    public function getExpediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpediente', []);

        return parent::getExpediente();
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultaCosto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultaCosto', []);

        return parent::getConsultaCosto();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function getMedico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedico', []);

        return parent::getMedico();
    }

    /**
     * {@inheritDoc}
     */
    public function getHigieneDentalConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHigieneDentalConsulta', []);

        return parent::getHigieneDentalConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function getIndicacionConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndicacionConsulta', []);

        return parent::getIndicacionConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarReceta(\Siacme\Dominio\Consultas\RecetaConsulta $receta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarReceta', [$receta]);

        return parent::agregarReceta($receta);
    }

    /**
     * {@inheritDoc}
     */
    public function agregarHigieneDental(\Siacme\Dominio\Consultas\HigieneDentalConsulta $higieneDental)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarHigieneDental', [$higieneDental]);

        return parent::agregarHigieneDental($higieneDental);
    }

    /**
     * {@inheritDoc}
     */
    public function agregarIndicacionConsulta(\Siacme\Dominio\Consultas\IndicacionConsulta $indicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarIndicacionConsulta', [$indicacion]);

        return parent::agregarIndicacionConsulta($indicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function generadaPara(\Siacme\Dominio\Expedientes\Expediente $expediente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generadaPara', [$expediente]);

        return parent::generadaPara($expediente);
    }

    /**
     * {@inheritDoc}
     */
    public function agregarCosto(\Siacme\Dominio\Consultas\ConsultaCosto $consultaCosto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarCosto', [$consultaCosto]);

        return parent::agregarCosto($consultaCosto);
    }

    /**
     * {@inheritDoc}
     */
    public function costoReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'costoReal', []);

        return parent::costoReal();
    }

    /**
     * {@inheritDoc}
     */
    public function desgloseCosto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'desgloseCosto', []);

        return parent::desgloseCosto();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarComentario($comentario = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarComentario', [$comentario]);

        return parent::agregarComentario($comentario);
    }

    /**
     * {@inheritDoc}
     */
    public function registrarPago(\Siacme\Dominio\Cobros\Cobro $cobroConsulta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'registrarPago', [$cobroConsulta]);

        return parent::registrarPago($cobroConsulta);
    }

    /**
     * {@inheritDoc}
     */
    public function costoFormateado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'costoFormateado', []);

        return parent::costoFormateado();
    }

    /**
     * {@inheritDoc}
     */
    public function costoRealFormateado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'costoRealFormateado', []);

        return parent::costoRealFormateado();
    }

    /**
     * {@inheritDoc}
     */
    public function getCobrosConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCobrosConsulta', []);

        return parent::getCobrosConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function getCostos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostos', []);

        return parent::getCostos();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarOtrosCostos($otroCosto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarOtrosCostos', [$otroCosto]);

        return parent::agregarOtrosCostos($otroCosto);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtrosCostos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtrosCostos', []);

        return parent::getOtrosCostos();
    }

    /**
     * {@inheritDoc}
     */
    public function getARealizarEnProximaCita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getARealizarEnProximaCita', []);

        return parent::getARealizarEnProximaCita();
    }

    /**
     * {@inheritDoc}
     */
    public function obtenerSaldo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'obtenerSaldo', []);

        return parent::obtenerSaldo();
    }

    /**
     * {@inheritDoc}
     */
    public function abonoMinimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'abonoMinimo', []);

        return parent::abonoMinimo();
    }

    /**
     * {@inheritDoc}
     */
    public function tieneHigieneDental()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneHigieneDental', []);

        return parent::tieneHigieneDental();
    }

    /**
     * {@inheritDoc}
     */
    public function tieneIndicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneIndicacion', []);

        return parent::tieneIndicacion();
    }

}
