<?php

namespace DoctrineProxies\__CG__\Siacme\Dominio\Pacientes;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paciente extends \Siacme\Dominio\Pacientes\Paciente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'domicilio', 'fechaNacimiento', 'edadAnios', 'edadMeses', 'lugarNacimiento', 'nombre', 'paterno', 'materno', 'sexo', 'telefono', 'celular', 'email'];
        }

        return ['__isInitialized__', 'id', 'domicilio', 'fechaNacimiento', 'edadAnios', 'edadMeses', 'lugarNacimiento', 'nombre', 'paterno', 'materno', 'sexo', 'telefono', 'celular', 'email'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paciente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function getEdadAnios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdadAnios', []);

        return parent::getEdadAnios();
    }

    /**
     * {@inheritDoc}
     */
    public function getEdadMeses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdadMeses', []);

        return parent::getEdadMeses();
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarNacimiento', []);

        return parent::getLugarNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function edadCompleta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'edadCompleta', []);

        return parent::edadCompleta();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarDatosPersonales($nombre, $paterno, $materno, \DateTime $fechaNacimiento, $lugarNacimiento, $telefono, $celular, $email, \Siacme\Dominio\Pacientes\Domicilio $domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarDatosPersonales', [$nombre, $paterno, $materno, $fechaNacimiento, $lugarNacimiento, $telefono, $celular, $email, $domicilio]);

        return parent::agregarDatosPersonales($nombre, $paterno, $materno, $fechaNacimiento, $lugarNacimiento, $telefono, $celular, $email, $domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaterno', []);

        return parent::getPaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterno', []);

        return parent::getMaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function nombreCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nombreCompleto', []);

        return parent::nombreCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular', []);

        return parent::getCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

}
