<?php

namespace DoctrineProxies\__CG__\Siacme\Dominio\Expedientes;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Diente extends \Siacme\Dominio\Expedientes\Diente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'numero', 'padecimientos', 'tratamientos', 'existe'];
        }

        return ['__isInitialized__', 'numero', 'padecimientos', 'tratamientos', 'existe'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Diente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNumero();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function getPadecimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadecimientos', []);

        return parent::getPadecimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function removerPadecimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removerPadecimientos', []);

        return parent::removerPadecimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarPadecimiento(\Siacme\Dominio\Expedientes\DientePadecimiento $padecimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarPadecimiento', [$padecimiento]);

        return parent::agregarPadecimiento($padecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTratamientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTratamientos', []);

        return parent::getTratamientos();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarTratamiento(\Siacme\Dominio\Expedientes\DienteTratamiento $tratamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarTratamiento', [$tratamiento]);

        return parent::agregarTratamiento($tratamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function removerTratamientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removerTratamientos', []);

        return parent::removerTratamientos();
    }

    /**
     * {@inheritDoc}
     */
    public function tieneElTratamientoAsignado(\Siacme\Dominio\Expedientes\DienteTratamiento $dienteTratamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneElTratamientoAsignado', [$dienteTratamiento]);

        return parent::tieneElTratamientoAsignado($dienteTratamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function eliminarTratamiento(\Siacme\Dominio\Expedientes\DienteTratamiento $dienteTratamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eliminarTratamiento', [$dienteTratamiento]);

        return parent::eliminarTratamiento($dienteTratamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function tieneTratamientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneTratamientos', []);

        return parent::tieneTratamientos();
    }

    /**
     * {@inheritDoc}
     */
    public function tienePadecimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tienePadecimientos', []);

        return parent::tienePadecimientos();
    }

}
